name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel numpy scipy cython

      - name: Build wheel
        run: python setup.py bdist_wheel

      # Install and run auditwheel if on Ubuntu
      - name: Install and Repair wheel with auditwheel
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          pip install auditwheel
          auditwheel repair dist/*.whl -w wheelhouse --plat manylinux2014_x86_64

      # Upload wheel from 'dist' directory for macOS and Windows
      - name: Upload wheel from dist
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./dist/*.whl

      # Upload wheel from 'wheelhouse' for Ubuntu
      - name: Upload wheel from wheelhouse
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
